services:
  - type: web
    name: hk-species-api
    env: python
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9